### ISSUE TITLE
use -a flag for usermod

### ISSUE THREAD

**Issue by scolytus** [TheMickeyMike/raspberrypi-temperature-telegraf#4]
Hi, thanks for sharing your work! :heart: 

You should add the `-a` flag to the `usermod` command.
As it is now, it would **remove** telegraf from all other groups.

`sudo usermod -a -G video telegraf`

I have telegraf also assigned to the `docker` and `unbound` group, your original command would remove it from those.

**Comment by TheMickeyMike** [comment]
Hello, thanks for pointing this out!
