### ISSUE TITLE
vcgencmd moved in recent versions of raspbian?

### ISSUE THREAD

**Issue by positron96** [TheMickeyMike/raspberrypi-temperature-telegraf#6]
Hi. I tried your config, but on my raspbian, `vcgencmd` is in /usr/bin/vcgencmd now, not in opt.

My version of deb package is
libraspberrypi-bin  1:2+git20220616~133208+6e8f786-1

**Comment by TheMickeyMike** [comment]
@positron96 you are right, thanks for creating this issue. Instruction & script updated.
